name: Release Extension

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run tests
      run: pnpm test

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run Biome lint
      run: pnpm run lint
      
    - name: Run Biome format check
      run: pnpm run format

  build-and-release:
    runs-on: ubuntu-latest
    needs: [test, lint]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
      
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Install glib-compile-schemas
      run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev-bin
      
    - name: Build extension
      run: pnpm run build:all
      
    - name: Package extension
      run: pnpm run pack
      
    - name: Verify package exists
      run: |
        if [ ! -f "openrgb-sync-accent-color.zip" ]; then
          echo "❌ Error: Extension package not found!"
          exit 1
        fi
        echo "✅ Package verified: $(ls -lh openrgb-sync-accent-color.zip)"
      
    - name: Upload to GNOME Extensions
      uses: fire-man-x/gnome-shell-extension-uploader@v1
      with:
        gnome_username: ${{ secrets.GNOME_EXTENSIONS_USERNAME }}
        gnome_password: ${{ secrets.GNOME_EXTENSIONS_PASSWORD }}
        extension_zip_file: 'openrgb-sync-accent-color.zip'

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        body: |
          ## Changes
          
          Automated release for version ${{ github.ref_name }}
          
          ## Installation
          
          1. Download the `.zip` file below
          2. Extract it to `~/.local/share/gnome-shell/extensions/`
          3. Restart GNOME Shell
          4. Enable the extension in GNOME Extensions app
          
          ## Requirements
          
          - GNOME Shell 45+
          - OpenRGB server running in background
        files: |
          openrgb-sync-accent-color.zip
        draft: false
        prerelease: false

    - name: Notify Success or Error
      if: always()
      run: |
        CHANNEL="${{ secrets.NTFY_CHANNEL }}"
        if [ "${{ job.status }}" == "success" ]; then
          curl -H "Title: Extension Reelease Success" -d "Check status about version ${{ github.event.release.tag_name }} at: https://extensions.gnome.org/extension/8331/openrgb-accent-color-sync/" ntfy.sh/$CHANNEL
        else
          curl -H "Title: Extension Reelease Failure" -d "Version ${{ github.event.release.tag_name }} not released" ntfy.sh/$CHANNEL
        fi
